#!/bin/bash

export HUBOT_XMPP_USERNAME=bosst@vanguard
export HUBOT_XMPP_PASSWORD=bosst
export HUBOT_XMPP_ROOMS=oss@conference.vanguard

export HUBOT_XMPP_HOST=127.0.0.1
export HUBOT_XMPP_PORT=5222

export PORT=8081

bin/hubot -a xmpp
