#!/bin/bash

export HUBOT_XMPP_USERNAME=rfranknj@rutgers.edu
export HUBOT_XMPP_PASSWORD=77033c31
export HUBOT_XMPP_ROOMS=oss@conference.rutgers.edu

export HUBOT_XMPP_HOST=rutgers.edu
export HUBOT_XMPP_PORT=5222

export PORT=8081

bin/hubot -a xmpp
